### ISSUE TITLE
main.14a48dd3440725b4171f.bundle.js:1 ERROR Error: Uncaught (in promise): TypeError: oo[t] is not a constructor

### ISSUE THREAD

**Issue by bigWebApps** [Angular-RU/angular-universal-starter#2]
Привет

спасибо за проект, очень интересно
при ssr ionic когда кликаю на меню - ошибка
В клиентском запуске все работает.

main.14a48dd3440725b4171f.bundle.js:1 ERROR Error: Uncaught (in promise): TypeError: oo[t] is not a constructor
TypeError: oo[t] is not a constructor
    at Function.LZ6q.t.create (main.14a48dd3440725b4171f.bundle.js:1)
    at t.LZ6q.t._getType (main.14a48dd3440725b4171f.bundle.js:1)
    at main.14a48dd3440725b4171f.bundle.js:1
    at new e (polyfills.ecf9b4b1345ca40dd032.bundle.js:1)
    at t.LZ6q.t.setOpen (main.14a48dd3440725b4171f.bundle.js:1)
    at t.LZ6q.t.toggle (main.14a48dd3440725b4171f.bundle.js:1)
    at t.LZ6q.t.toggle (main.14a48dd3440725b4171f.bundle.js:1)
    at Object.handleEvent (main.14a48dd3440725b4171f.bundle.js:1)
    at Object.handleEvent (main.14a48dd3440725b4171f.bundle.js:1)
    at Object.handleEvent (main.14a48dd3440725b4171f.bundle.js:1)
    at Function.LZ6q.t.create (main.14a48dd3440725b4171f.bundle.js:1)
    at t.LZ6q.t._getType (main.14a48dd3440725b4171f.bundle.js:1)
    at main.14a48dd3440725b4171f.bundle.js:1
    at new e (polyfills.ecf9b4b1345ca40dd032.bundle.js:1)
    at t.LZ6q.t.setOpen (main.14a48dd3440725b4171f.bundle.js:1)
    at t.LZ6q.t.toggle (main.14a48dd3440725b4171f.bundle.js:1)
    at t.LZ6q.t.toggle (main.14a48dd3440725b4171f.bundle.js:1)
    at Object.handleEvent (main.14a48dd3440725b4171f.bundle.js:1)
    at Object.handleEvent (main.14a48dd3440725b4171f.bundle.js:1)
    at Object.handleEvent (main.14a48dd3440725b4171f.bundle.js:1)
    at i (polyfills.ecf9b4b1345ca40dd032.bundle.js:1)
    at new e (polyfills.ecf9b4b1345ca40dd032.bundle.js:1)
    at t.LZ6q.t.setOpen (main.14a48dd3440725b4171f.bundle.js:1)
    at t.LZ6q.t.toggle (main.14a48dd3440725b4171f.bundle.js:1)
    at t.LZ6q.t.toggle (main.14a48dd3440725b4171f.bundle.js:1)
    at Object.handleEvent (main.14a48dd3440725b4171f.bundle.js:1)
    at Object.handleEvent (main.14a48dd3440725b4171f.bundle.js:1)
    at Object.handleEvent (main.14a48dd3440725b4171f.bundle.js:1)
    at Ft (main.14a48dd3440725b4171f.bundle.js:1)
    at main.14a48dd3440725b4171f.bundle.js:1

WARNING in ./node_modules/ionic-angular/util/ng-module-loader.js
20:11-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (c:\__WORK\angular-universal-star
ter-ionic\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (c:\__WORK\angular-universa
l-starter-ionic\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (c:\__WORK\angular-universal-starter-ionic\node_module
s\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (c:\__WORK\angular-universal-starter-ionic\node_
modules\webpack\lib\Compiler.js:506:17)
    at c:\__WORK\angular-universal-starter-ionic\node_modules\tapable\lib\Tapabl
e.js:289:11
    at _addModuleChain (c:\__WORK\angular-universal-starter-ionic\node_modules\w
ebpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (c:\__WORK\angular-universal-starter-ionic\
node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/ionic-angular/util/ng-module-loader.js
 @ ./node_modules/ionic-angular/util/module-loader.js
 @ ./node_modules/ionic-angular/components/modal/modal-component.ngfactory.js
 @ ./src/app/app.server.module.ngfactory.js
 @ ./src/main.server.ts
 @ multi ./src/main.server.ts

WARNING in ./node_modules/ionic-angular/util/ng-module-loader.js
30:11-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (c:\__WORK\angular-universal-star
ter-ionic\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (c:\__WORK\angular-universa
l-starter-ionic\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (c:\__WORK\angular-universal-starter-ionic\node_module
s\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (c:\__WORK\angular-universal-starter-ionic\node_
modules\webpack\lib\Compiler.js:506:17)
    at c:\__WORK\angular-universal-starter-ionic\node_modules\tapable\lib\Tapabl
e.js:289:11
    at _addModuleChain (c:\__WORK\angular-universal-starter-ionic\node_modules\w
ebpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (c:\__WORK\angular-universal-starter-ionic\
node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/ionic-angular/util/ng-module-loader.js
 @ ./node_modules/ionic-angular/util/module-loader.js
 @ ./node_modules/ionic-angular/components/modal/modal-component.ngfactory.js
 @ ./src/app/app.server.module.ngfactory.js
 @ ./src/main.server.ts
 @ multi ./src/main.server.ts
Hash: 7ecea4c34738c7ab1138
Version: webpack 3.8.1
Time: 3659ms
       Asset     Size  Chunks                    Chunk Names
   server.js  6.92 MB       0  [emitted]  [big]  server
prerender.js  6.21 MB       1  [emitted]  [big]  prerender
 [184] ./src lazy 160 bytes {0} {1} [built]
 [198] ./node_modules/ionic-angular/util lazy 160 bytes {0} {1} [built]
 [317] ./dist-server ^\.\/main\..*\.bundle$ 199 bytes {0} {1} [built]
 [318] ./dist-server/main.9a5f0bf3c5db9fd29623.bundle.js 263 kB {0} {1} [optiona
l] [built]
 [419] ./server.ts 2.6 kB {0} [built]
 [469] ./src 160 bytes {0} [built]
 [475] (webpack)/buildin/module.js 495 bytes {0} [built]
 [489] ./prerender.ts 1.91 kB {1} [built]
 [490] ./static.paths.ts 52 bytes {1} [built]
    + 482 hidden modules

WARNING in ./node_modules/ionic-angular/util/ng-module-loader.js
27:11-36 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/ionic-angular/util/ng-module-loader.js
 @ ./dist-server/main.9a5f0bf3c5db9fd29623.bundle.js
 @ ./dist-server ^\.\/main\..*\.bundle$
 @ ./server.ts

WARNING in ./node_modules/ionic-angular/util/ng-module-loader.js
37:11-36 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/ionic-angular/util/ng-module-loader.js
 @ ./dist-server/main.9a5f0bf3c5db9fd29623.bundle.js
 @ ./dist-server ^\.\/main\..*\.bundle$
 @ ./server.ts

**Comment by Gorniv** [comment]
Да, там сейчас куча проблем. если запустить `npm run ssr:debug`  ошибка будет понятнее. К сожалению я не понимаю что ему надо. Он пишет что `no provide Config` - я перепробовал кучу всего, но не понимаю что сейчас надо сделать. К сожалению команда ionic сейчас активно пилит новую версию на базе https://github.com/ionic-team/stencil и не собирается поддерживать universal ( https://github.com/ionic-team/ionic/issues/10699 )
