### ISSUE TITLE
Error after "npm run ssr" - Can't set headers after they are sent.

### ISSUE THREAD

**Issue by yacineblr** [Angular-RU/angular-universal-starter#54]
Hi, I have a problem launching the project with "npm run ssr" just after git clone project and npm install.
I haven't changed anything.

>ORIGIN_URL=http://localhost:4000
> universal-demo@6.1.0 server /home/lenovo/Documents/tmp/unistarter
> node server.js
>listening on http://localhost:4000!
>GET: /home: 113.256ms
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/home/lenovo/Documents/tmp/unistarter/node_modules/send/index.js:390:13)
    at SendStream.send (/home/lenovo/Documents/tmp/unistarter/node_modules/send/index.js:618:10)
    at onstat (/home/lenovo/Documents/tmp/unistarter/node_modules/send/index.js:730:10)
    at ZoneDelegate.invokeTask (/home/lenovo/Documents/tmp/unistarter/node_modules/zone.js/dist/zone-node.js:421:31)
    at Zone.runTask (/home/lenovo/Documents/tmp/unistarter/node_modules/zone.js/dist/zone-node.js:188:47)
    at ZoneTask.invokeTask (/home/lenovo/Documents/tmp/unistarter/node_modules/zone.js/dist/zone-node.js:496:34)
    at ZoneTask.invoke (/home/lenovo/Documents/tmp/unistarter/node_modules/zone.js/dist/zone-node.js:485:48)
    at data.args.(anonymous function) (/home/lenovo/Documents/tmp/unistarter/node_modules/zone.js/dist/zone-node.js:1317:25)
    at FSReqWrap.oncomplete (fs.js:153:5)

My config is:
Ubuntu 16.04
Node v8.11.3
Npm 5.6.0

**Comment by shahbazkhan054** [comment]
Please check the express settings for redirection. It's getting redirected by your node or nginx server.
